# Generated by Django 5.1.7 on 2025-03-23 22:38

from django.db import migrations

def convert_ip_to_inet(apps, schema_editor):
    """
    Convert ip column to PostgreSQL inet type.
    Silently skip for non-PostgreSQL backends (e.g. SQLite tests).
    """
    if schema_editor.connection.vendor != "postgresql":
        # SQLite / others: do nothing
        print("Skipping inet conversion (not PostgreSQL).")
        return

    schema_editor.execute(
        "ALTER TABLE portal_ipaddress "
        "ALTER COLUMN ip TYPE inet USING (ip::inet);"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(convert_ip_to_inet),
    ]
