# Generated by Django 5.1.6 on 2026-02-13 19:53

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_fix_ip_type'),
        ("auth", "0012_alter_user_first_name_max_length"),  # latest auth migration
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE auth_user ALTER COLUMN last_login DROP NOT NULL;",
            reverse_sql="ALTER TABLE auth_user ALTER COLUMN last_login SET NOT NULL;",
        ),
    ]
