name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7] # TODO: python3 support, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Build Container Image
      run: docker build --build-arg PYTHON_VERSION=${{ matrix.python-version }} -t dns-portal .
    - name: Run Tests
      run: |
        docker run --rm dns-portal manage.py test
